### ISSUE TITLE
Не обновляется government-blacklist.txt

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/LibertyTunnel#2]
Указал для обновления линк адреса списка блокировок с антизапрета, но файл https://antizapret.prostovpn.org/domains-export.txt так и не выкачался. В итоге пришло качать ручками, ренеймить и ложить в configs - папку. На ведре та же ситуация кстати.

**Comment by krlvm** [comment]
Это сделано намерено.

Если при запуске сервера не произошла ошибка, значит список заблокированных адресов успешно загрузился в память, хотя в файл они не сохраняются, так как в этом, как мне кажется, нет нужды.

**Comment by Baltazar500** [comment]
>так как в этом, как мне кажется, нет нужды

А если сервер того же антизапрета не будет доступен какое-то время ? Тогда весь трафик ломанётся через прокси :/

**Comment by krlvm** [comment]
Согласен, нужно добавить опцию для сохранения списка в локальный файл
